//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

// Defines values for PunishmentType.
const (
	PunishmentTypeBan     PunishmentType = "ban"
	PunishmentTypeKick    PunishmentType = "kick"
	PunishmentTypeMute    PunishmentType = "mute"
	PunishmentTypeWarning PunishmentType = "warning"
)

// Valid indicates whether the value is a known member of the PunishmentType enum.
func (e PunishmentType) Valid() bool {
	switch e {
	case PunishmentTypeBan:
		return true
	case PunishmentTypeKick:
		return true
	case PunishmentTypeMute:
		return true
	case PunishmentTypeWarning:
		return true
	default:
		return false
	}
}

// Defines values for TypeSingularQuery.
const (
	TypeSingularQueryBan     TypeSingularQuery = "ban"
	TypeSingularQueryKick    TypeSingularQuery = "kick"
	TypeSingularQueryMute    TypeSingularQuery = "mute"
	TypeSingularQueryWarning TypeSingularQuery = "warning"
)

// Valid indicates whether the value is a known member of the TypeSingularQuery enum.
func (e TypeSingularQuery) Valid() bool {
	switch e {
	case TypeSingularQueryBan:
		return true
	case TypeSingularQueryKick:
		return true
	case TypeSingularQueryMute:
		return true
	case TypeSingularQueryWarning:
		return true
	default:
		return false
	}
}

// Defines values for GetModPunishmentsListParamsType.
const (
	GetModPunishmentsListParamsTypeBan     GetModPunishmentsListParamsType = "ban"
	GetModPunishmentsListParamsTypeKick    GetModPunishmentsListParamsType = "kick"
	GetModPunishmentsListParamsTypeMute    GetModPunishmentsListParamsType = "mute"
	GetModPunishmentsListParamsTypeWarning GetModPunishmentsListParamsType = "warning"
)

// Valid indicates whether the value is a known member of the GetModPunishmentsListParamsType enum.
func (e GetModPunishmentsListParamsType) Valid() bool {
	switch e {
	case GetModPunishmentsListParamsTypeBan:
		return true
	case GetModPunishmentsListParamsTypeKick:
		return true
	case GetModPunishmentsListParamsTypeMute:
		return true
	case GetModPunishmentsListParamsTypeWarning:
		return true
	default:
		return false
	}
}

// Defines values for GetPlayerPunishmentsMeParamsType.
const (
	GetPlayerPunishmentsMeParamsTypeBan     GetPlayerPunishmentsMeParamsType = "ban"
	GetPlayerPunishmentsMeParamsTypeKick    GetPlayerPunishmentsMeParamsType = "kick"
	GetPlayerPunishmentsMeParamsTypeMute    GetPlayerPunishmentsMeParamsType = "mute"
	GetPlayerPunishmentsMeParamsTypeWarning GetPlayerPunishmentsMeParamsType = "warning"
)

// Valid indicates whether the value is a known member of the GetPlayerPunishmentsMeParamsType enum.
func (e GetPlayerPunishmentsMeParamsType) Valid() bool {
	switch e {
	case GetPlayerPunishmentsMeParamsTypeBan:
		return true
	case GetPlayerPunishmentsMeParamsTypeKick:
		return true
	case GetPlayerPunishmentsMeParamsTypeMute:
		return true
	case GetPlayerPunishmentsMeParamsTypeWarning:
		return true
	default:
		return false
	}
}

// Defines values for GetPunishmentByIDParamsType.
const (
	Bans     GetPunishmentByIDParamsType = "bans"
	Kicks    GetPunishmentByIDParamsType = "kicks"
	Mutes    GetPunishmentByIDParamsType = "mutes"
	Warnings GetPunishmentByIDParamsType = "warnings"
)

// Valid indicates whether the value is a known member of the GetPunishmentByIDParamsType enum.
func (e GetPunishmentByIDParamsType) Valid() bool {
	switch e {
	case Bans:
		return true
	case Kicks:
		return true
	case Mutes:
		return true
	case Warnings:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   string `json:"error"`
	Message string `json:"message"`
}

// Moderator defines model for Moderator.
type Moderator struct {
	IsConsole bool    `json:"isConsole"`
	Name      *string `json:"name,omitempty"`
	Uuid      *string `json:"uuid,omitempty"`
}

// Player defines model for Player.
type Player struct {
	IsConsole   bool    `json:"isConsole"`
	Name        *string `json:"name,omitempty"`
	OfflineMode bool    `json:"offlineMode"`
	Uuid        *string `json:"uuid,omitempty"`
}

// Punishment defines model for Punishment.
type Punishment struct {
	Acknowledged *bool  `json:"acknowledged,omitempty"`
	Active       *bool  `json:"active,omitempty"`
	Expired      *bool  `json:"expired,omitempty"`
	ExpiresAt    *int64 `json:"expiresAt,omitempty"`

	// Id Punishment id; numeric or obfuscated string depending on server configuration.
	Id           interface{}    `json:"id"`
	IpBan        *bool          `json:"ipBan,omitempty"`
	IssuedAt     int64          `json:"issuedAt"`
	Moderator    Moderator      `json:"moderator"`
	Permanent    *bool          `json:"permanent,omitempty"`
	PlayerUuid   string         `json:"playerUuid"`
	Reason       string         `json:"reason"`
	Removed      *Removed       `json:"removed,omitempty"`
	ServerOrigin *string        `json:"serverOrigin"`
	ServerScope  *string        `json:"serverScope,omitempty"`
	Silent       *bool          `json:"silent,omitempty"`
	Type         PunishmentType `json:"type"`
}

// PunishmentType defines model for Punishment.Type.
type PunishmentType string

// PunishmentList defines model for PunishmentList.
type PunishmentList struct {
	Items      []Punishment `json:"items"`
	Page       int32        `json:"page"`
	PageSize   int32        `json:"pageSize"`
	TotalItems int64        `json:"totalItems"`
	TotalPages int32        `json:"totalPages"`
}

// Removed defines model for Removed.
type Removed struct {
	At                   int64     `json:"at"`
	By                   Moderator `json:"by"`
	ExpiredAutomatically bool      `json:"expiredAutomatically"`
	Reason               *string   `json:"reason,omitempty"`
}

// Stats defines model for Stats.
type Stats struct {
	Bans     int64 `json:"bans"`
	Kicks    int64 `json:"kicks"`
	Mutes    int64 `json:"mutes"`
	Warnings int64 `json:"warnings"`
}

// Active defines model for Active.
type Active = bool

// ModeratorUuid defines model for ModeratorUuid.
type ModeratorUuid = string

// Page defines model for Page.
type Page = int32

// PageSize defines model for PageSize.
type PageSize = int32

// PlayerUuid defines model for PlayerUuid.
type PlayerUuid = string

// Silent defines model for Silent.
type Silent = bool

// TypeQuery defines model for TypeQuery.
type TypeQuery = string

// TypeSingularQuery defines model for TypeSingularQuery.
type TypeSingularQuery string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// GetModPunishmentsListParams defines parameters for GetModPunishmentsList.
type GetModPunishmentsListParams struct {
	Type          *GetModPunishmentsListParamsType `form:"type,omitempty" json:"type,omitempty"`
	PlayerUuid    *PlayerUuid                      `form:"playerUuid,omitempty" json:"playerUuid,omitempty"`
	ModeratorUuid *ModeratorUuid                   `form:"moderatorUuid,omitempty" json:"moderatorUuid,omitempty"`
	Active        *Active                          `form:"active,omitempty" json:"active,omitempty"`
	Silent        *Silent                          `form:"silent,omitempty" json:"silent,omitempty"`
	Page          *Page                            `form:"page,omitempty" json:"page,omitempty"`
	PageSize      *PageSize                        `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetModPunishmentsListParamsType defines parameters for GetModPunishmentsList.
type GetModPunishmentsListParamsType string

// GetPlayerPunishmentsMeParams defines parameters for GetPlayerPunishmentsMe.
type GetPlayerPunishmentsMeParams struct {
	Type          *GetPlayerPunishmentsMeParamsType `form:"type,omitempty" json:"type,omitempty"`
	ModeratorUuid *ModeratorUuid                    `form:"moderatorUuid,omitempty" json:"moderatorUuid,omitempty"`
	Before        *int64                            `form:"before,omitempty" json:"before,omitempty"`
	After         *int64                            `form:"after,omitempty" json:"after,omitempty"`
	Page          *Page                             `form:"page,omitempty" json:"page,omitempty"`
	PageSize      *PageSize                         `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetPlayerPunishmentsMeParamsType defines parameters for GetPlayerPunishmentsMe.
type GetPlayerPunishmentsMeParamsType string

// GetPublicLookupParams defines parameters for GetPublicLookup.
type GetPublicLookupParams struct {
	Name          *string `form:"name,omitempty" json:"name,omitempty"`
	Uuid          *string `form:"uuid,omitempty" json:"uuid,omitempty"`
	ModeratorName *string `form:"moderatorName,omitempty" json:"moderatorName,omitempty"`
	ModeratorUuid *string `form:"moderatorUuid,omitempty" json:"moderatorUuid,omitempty"`
}

// GetPublicPunishmentsParams defines parameters for GetPublicPunishments.
type GetPublicPunishmentsParams struct {
	Type          *TypeQuery     `form:"type,omitempty" json:"type,omitempty"`
	Page          *Page          `form:"page,omitempty" json:"page,omitempty"`
	PageSize      *PageSize      `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	Active        *Active        `form:"active,omitempty" json:"active,omitempty"`
	Silent        *Silent        `form:"silent,omitempty" json:"silent,omitempty"`
	PlayerUuid    *PlayerUuid    `form:"playerUuid,omitempty" json:"playerUuid,omitempty"`
	ModeratorUuid *ModeratorUuid `form:"moderatorUuid,omitempty" json:"moderatorUuid,omitempty"`
}

// GetPunishmentByIDParamsType defines parameters for GetPunishmentByID.
type GetPunishmentByIDParamsType string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Full punishments listing across all players/moderators (requires moderator permission)
	// (GET /api/v1/mod/punishments/list)
	GetModPunishmentsList(w http.ResponseWriter, r *http.Request, params GetModPunishmentsListParams)
	// The caller's own punishments across all types (requires JWT)
	// (GET /api/v1/player/punishments/me)
	GetPlayerPunishmentsMe(w http.ResponseWriter, r *http.Request, params GetPlayerPunishmentsMeParams)
	// Resolve a player/moderator identity by name or uuid
	// (GET /api/v1/public/lookup)
	GetPublicLookup(w http.ResponseWriter, r *http.Request, params GetPublicLookupParams)
	// List publicly visible punishments of a single (whitelisted) type
	// (GET /api/v1/public/punishments)
	GetPublicPunishments(w http.ResponseWriter, r *http.Request, params GetPublicPunishmentsParams)
	// Aggregate punishment counters
	// (GET /api/v1/public/punishments/stats)
	GetPublicPunishmentsStats(w http.ResponseWriter, r *http.Request)
	// Contextual punishment lookup; JWT optional, authorized after load
	// (GET /api/v1/punishments/{type}/{id})
	GetPunishmentByID(w http.ResponseWriter, r *http.Request, pType GetPunishmentByIDParamsType, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetModPunishmentsList operation middleware
func (siw *ServerInterfaceWrapper) GetModPunishmentsList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetModPunishmentsListParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "playerUuid" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "playerUuid", r.URL.Query(), &params.PlayerUuid, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "playerUuid"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playerUuid", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "moderatorUuid" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "moderatorUuid", r.URL.Query(), &params.ModeratorUuid, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "moderatorUuid"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "moderatorUuid", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "active" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "active", r.URL.Query(), &params.Active, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "active"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "active", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "silent" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "silent", r.URL.Query(), &params.Silent, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "silent"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "silent", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetModPunishmentsList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlayerPunishmentsMe operation middleware
func (siw *ServerInterfaceWrapper) GetPlayerPunishmentsMe(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPlayerPunishmentsMeParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "moderatorUuid" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "moderatorUuid", r.URL.Query(), &params.ModeratorUuid, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "moderatorUuid"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "moderatorUuid", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlayerPunishmentsMe(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicLookup operation middleware
func (siw *ServerInterfaceWrapper) GetPublicLookup(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPublicLookupParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "name", r.URL.Query(), &params.Name, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "name"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "uuid" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "uuid", r.URL.Query(), &params.Uuid, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "uuid"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "moderatorName" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "moderatorName", r.URL.Query(), &params.ModeratorName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "moderatorName"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "moderatorName", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "moderatorUuid" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "moderatorUuid", r.URL.Query(), &params.ModeratorUuid, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "moderatorUuid"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "moderatorUuid", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicLookup(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicPunishments operation middleware
func (siw *ServerInterfaceWrapper) GetPublicPunishments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPublicPunishmentsParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "active" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "active", r.URL.Query(), &params.Active, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "active"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "active", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "silent" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "silent", r.URL.Query(), &params.Silent, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "silent"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "silent", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "playerUuid" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "playerUuid", r.URL.Query(), &params.PlayerUuid, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "playerUuid"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playerUuid", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "moderatorUuid" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "moderatorUuid", r.URL.Query(), &params.ModeratorUuid, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "moderatorUuid"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "moderatorUuid", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicPunishments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicPunishmentsStats operation middleware
func (siw *ServerInterfaceWrapper) GetPublicPunishmentsStats(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicPunishmentsStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPunishmentByID operation middleware
func (siw *ServerInterfaceWrapper) GetPunishmentByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "type" -------------
	var pType GetPunishmentByIDParamsType

	err = runtime.BindStyledParameterWithOptions("simple", "type", r.PathValue("type"), &pType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPunishmentByID(w, r, pType, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/mod/punishments/list", wrapper.GetModPunishmentsList)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/player/punishments/me", wrapper.GetPlayerPunishmentsMe)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/public/lookup", wrapper.GetPublicLookup)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/public/punishments", wrapper.GetPublicPunishments)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/public/punishments/stats", wrapper.GetPublicPunishmentsStats)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/punishments/{type}/{id}", wrapper.GetPunishmentByID)

	return m
}

type BadRequestJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type ServiceUnavailableJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type GetModPunishmentsListRequestObject struct {
	Params GetModPunishmentsListParams
}

type GetModPunishmentsListResponseObject interface {
	VisitGetModPunishmentsListResponse(w http.ResponseWriter) error
}

type GetModPunishmentsList200JSONResponse PunishmentList

func (response GetModPunishmentsList200JSONResponse) VisitGetModPunishmentsListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetModPunishmentsList400JSONResponse struct{ BadRequestJSONResponse }

func (response GetModPunishmentsList400JSONResponse) VisitGetModPunishmentsListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetModPunishmentsList401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetModPunishmentsList401JSONResponse) VisitGetModPunishmentsListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetModPunishmentsList403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetModPunishmentsList403JSONResponse) VisitGetModPunishmentsListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetModPunishmentsList500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetModPunishmentsList500JSONResponse) VisitGetModPunishmentsListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetModPunishmentsList503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetModPunishmentsList503JSONResponse) VisitGetModPunishmentsListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlayerPunishmentsMeRequestObject struct {
	Params GetPlayerPunishmentsMeParams
}

type GetPlayerPunishmentsMeResponseObject interface {
	VisitGetPlayerPunishmentsMeResponse(w http.ResponseWriter) error
}

type GetPlayerPunishmentsMe200JSONResponse PunishmentList

func (response GetPlayerPunishmentsMe200JSONResponse) VisitGetPlayerPunishmentsMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlayerPunishmentsMe400JSONResponse struct{ BadRequestJSONResponse }

func (response GetPlayerPunishmentsMe400JSONResponse) VisitGetPlayerPunishmentsMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlayerPunishmentsMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetPlayerPunishmentsMe401JSONResponse) VisitGetPlayerPunishmentsMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlayerPunishmentsMe500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetPlayerPunishmentsMe500JSONResponse) VisitGetPlayerPunishmentsMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicLookupRequestObject struct {
	Params GetPublicLookupParams
}

type GetPublicLookupResponseObject interface {
	VisitGetPublicLookupResponse(w http.ResponseWriter) error
}

type GetPublicLookup200JSONResponse Player

func (response GetPublicLookup200JSONResponse) VisitGetPublicLookupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicLookup400JSONResponse struct{ BadRequestJSONResponse }

func (response GetPublicLookup400JSONResponse) VisitGetPublicLookupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicLookup404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPublicLookup404JSONResponse) VisitGetPublicLookupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicLookup503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetPublicLookup503JSONResponse) VisitGetPublicLookupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicPunishmentsRequestObject struct {
	Params GetPublicPunishmentsParams
}

type GetPublicPunishmentsResponseObject interface {
	VisitGetPublicPunishmentsResponse(w http.ResponseWriter) error
}

type GetPublicPunishments200JSONResponse PunishmentList

func (response GetPublicPunishments200JSONResponse) VisitGetPublicPunishmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicPunishments400JSONResponse struct{ BadRequestJSONResponse }

func (response GetPublicPunishments400JSONResponse) VisitGetPublicPunishmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicPunishments500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetPublicPunishments500JSONResponse) VisitGetPublicPunishmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicPunishments503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetPublicPunishments503JSONResponse) VisitGetPublicPunishmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicPunishmentsStatsRequestObject struct {
}

type GetPublicPunishmentsStatsResponseObject interface {
	VisitGetPublicPunishmentsStatsResponse(w http.ResponseWriter) error
}

type GetPublicPunishmentsStats200JSONResponse Stats

func (response GetPublicPunishmentsStats200JSONResponse) VisitGetPublicPunishmentsStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicPunishmentsStats500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetPublicPunishmentsStats500JSONResponse) VisitGetPublicPunishmentsStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicPunishmentsStats503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetPublicPunishmentsStats503JSONResponse) VisitGetPublicPunishmentsStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetPunishmentByIDRequestObject struct {
	Type GetPunishmentByIDParamsType `json:"type"`
	Id   string                      `json:"id"`
}

type GetPunishmentByIDResponseObject interface {
	VisitGetPunishmentByIDResponse(w http.ResponseWriter) error
}

type GetPunishmentByID200JSONResponse Punishment

func (response GetPunishmentByID200JSONResponse) VisitGetPunishmentByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPunishmentByID400JSONResponse struct{ BadRequestJSONResponse }

func (response GetPunishmentByID400JSONResponse) VisitGetPunishmentByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetPunishmentByID404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPunishmentByID404JSONResponse) VisitGetPunishmentByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPunishmentByID500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetPunishmentByID500JSONResponse) VisitGetPunishmentByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Full punishments listing across all players/moderators (requires moderator permission)
	// (GET /api/v1/mod/punishments/list)
	GetModPunishmentsList(ctx context.Context, request GetModPunishmentsListRequestObject) (GetModPunishmentsListResponseObject, error)
	// The caller's own punishments across all types (requires JWT)
	// (GET /api/v1/player/punishments/me)
	GetPlayerPunishmentsMe(ctx context.Context, request GetPlayerPunishmentsMeRequestObject) (GetPlayerPunishmentsMeResponseObject, error)
	// Resolve a player/moderator identity by name or uuid
	// (GET /api/v1/public/lookup)
	GetPublicLookup(ctx context.Context, request GetPublicLookupRequestObject) (GetPublicLookupResponseObject, error)
	// List publicly visible punishments of a single (whitelisted) type
	// (GET /api/v1/public/punishments)
	GetPublicPunishments(ctx context.Context, request GetPublicPunishmentsRequestObject) (GetPublicPunishmentsResponseObject, error)
	// Aggregate punishment counters
	// (GET /api/v1/public/punishments/stats)
	GetPublicPunishmentsStats(ctx context.Context, request GetPublicPunishmentsStatsRequestObject) (GetPublicPunishmentsStatsResponseObject, error)
	// Contextual punishment lookup; JWT optional, authorized after load
	// (GET /api/v1/punishments/{type}/{id})
	GetPunishmentByID(ctx context.Context, request GetPunishmentByIDRequestObject) (GetPunishmentByIDResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetModPunishmentsList operation middleware
func (sh *strictHandler) GetModPunishmentsList(w http.ResponseWriter, r *http.Request, params GetModPunishmentsListParams) {
	var request GetModPunishmentsListRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetModPunishmentsList(ctx, request.(GetModPunishmentsListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetModPunishmentsList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetModPunishmentsListResponseObject); ok {
		if err := validResponse.VisitGetModPunishmentsListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPlayerPunishmentsMe operation middleware
func (sh *strictHandler) GetPlayerPunishmentsMe(w http.ResponseWriter, r *http.Request, params GetPlayerPunishmentsMeParams) {
	var request GetPlayerPunishmentsMeRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlayerPunishmentsMe(ctx, request.(GetPlayerPunishmentsMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlayerPunishmentsMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPlayerPunishmentsMeResponseObject); ok {
		if err := validResponse.VisitGetPlayerPunishmentsMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPublicLookup operation middleware
func (sh *strictHandler) GetPublicLookup(w http.ResponseWriter, r *http.Request, params GetPublicLookupParams) {
	var request GetPublicLookupRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPublicLookup(ctx, request.(GetPublicLookupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPublicLookup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPublicLookupResponseObject); ok {
		if err := validResponse.VisitGetPublicLookupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPublicPunishments operation middleware
func (sh *strictHandler) GetPublicPunishments(w http.ResponseWriter, r *http.Request, params GetPublicPunishmentsParams) {
	var request GetPublicPunishmentsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPublicPunishments(ctx, request.(GetPublicPunishmentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPublicPunishments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPublicPunishmentsResponseObject); ok {
		if err := validResponse.VisitGetPublicPunishmentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPublicPunishmentsStats operation middleware
func (sh *strictHandler) GetPublicPunishmentsStats(w http.ResponseWriter, r *http.Request) {
	var request GetPublicPunishmentsStatsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPublicPunishmentsStats(ctx, request.(GetPublicPunishmentsStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPublicPunishmentsStats")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPublicPunishmentsStatsResponseObject); ok {
		if err := validResponse.VisitGetPublicPunishmentsStatsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPunishmentByID operation middleware
func (sh *strictHandler) GetPunishmentByID(w http.ResponseWriter, r *http.Request, pType GetPunishmentByIDParamsType, id string) {
	var request GetPunishmentByIDRequestObject

	request.Type = pType
	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPunishmentByID(ctx, request.(GetPunishmentByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPunishmentByID")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPunishmentByIDResponseObject); ok {
		if err := validResponse.VisitGetPunishmentByIDResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
